### ISSUE TITLE
[Proposal] APAC Region TAG Meeting

### ISSUE THREAD

**Issue by eddie-knight** [cncf/tag-security#1322]
@PushkarJ @mnm678 and @eddie-knight are currently leading the exploration of a new APAC regional TAG meeting. Discussion is ongoing, and notes are below.

- We launch the first APAC meeting in 5-6 weeks, once we have some more planning complete.
- We create an initiative that the APAC community can lead and invite others into. This will be on the topic of Identity & Access.
- We create a working group that will allow the APAC community to lead and support the rest of the global community. This will be on the topic of Community Events.

**Comment by matthewflannery** [comment]
Hey @eddie-knight 

I previously ran these. After 6 meetings went by with zero attendance, we decided to can them. 

I'm absolutely for APAC TZ friendly meetings, but the reality is that the majority of STAG members are in US/EU based timezones.

Aside from that issue, the other issue is that without someone in the APAC time zone, or someone outside of it who can attend the regular STAG meetings its difficult to share ongoing progress for the purpose of meaningful collaboration. @JustinCappos previously did this for the APAC meetings before they became inactive.

My two cents on starting this up again is to perhaps find active issues or a project that can be collaborated on with fellow APAC timezone based individuals. That way at least you're guaranteed to have attendance to the meeting. 

A few of us are actively trying to grow contributors to CNCF & STAG in Australia/NZ. One key initiative is the upcoming KCD in September - would love to see you there and chat about the birds and the bees. 

With all of that said.. I'd be happy to attend APAC based meetings if they did start up again.

**Comment by eddie-knight** [comment]
Thanks @matthewflannery! This is really good insight, and I'd love to get you in the next discussion on this topic.

**Comment by matthewflannery** [comment]
> Thanks @matthewflannery! This is really good insight, and I'd love to get you in the next discussion on this topic.

I'm happy to talk to you about it. As mentioned, I started this previously but it was realistically just myself and 3 others, and then only myself and Justin.

Since then, I started KCD here in Aus. Last year, we had a 450~ pax attendance which was a great result. I've been trying to grow the CNCF community here in Australia but it is difficult, with limited support and being entirely self funded.

To be completely transparent - one of the reasons I started KCD here was to grow the community and hopefully find others whom will be willing to work on CNCF projects so that I'm not all alone, and I was planning to restart APAC based meetings when there was enough interest. Hence why I suggested maybe you should actually try to find some AU/NZ members whom will attend the meetings rather than just starting them.

As you likely know, I've contributed to several STAG projects most recently co-leading Automated Governance. I've tried to use LinkedIn and mentioning this project at other local meetups, and plan to bring it up on stage at KCD Sydney later this year in an effort to gain more APAC based contributors, but the reality is here is that Open Source development does not have the same community or support from companies in Australia/NZ as it does within say, USA. Take your role in Sonatype for example. We just simply don't have many / if any of those roles here. It's not all grim, there are a few CNCF contributors in AU/NZ, @bradmccoydev for e.g. who I work with actively through open source and community initiatives. Certainly though the community is not as large as other regions.

Please don't take this as pessimistic as I am in fact actively trying to grow CNCF here. Im sharing this to give you a taste of reality as it's difficult for you to be able to relate not being on the ground here. 

I'll continue to drive CNCF here and if you'd like to help, feel free to reach out to me on Slack.

**Comment by y-tabata** [comment]
After discussions with the TAG Chairs, I would like to volunteer to host a trial APAC community meeting on August 21st at 11 am JST.

**Comment by eddie-knight** [comment]
@riaankleinhans — would you be able to set up an LFX recurring meeting for this?

**Comment by riaankleinhans** [comment]
I have created the meeting, added it to the [TAG Security Calendar](https://calendar.google.com/calendar/u/0?cid=MGI4dTVlbDh0YTRzOTN0MmNtNzJ0dXZoaGtAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ), [CNCF Community Calendar](https://www.cncf.io/calendar/), and [CNCF PCC calendar](https://zoom-lfx.platform.linuxfoundation.org/meetings/cncf?view=week).
This is not are recurring meeting. Would you like me set it as recurring?

**Comment by eddie-knight** [comment]
Thank you @riaankleinhans! Yes, it should be recurring, fortnightly

**Comment by riaankleinhans** [comment]
Updated to be fortnightly. Please check all calendars. That should close this issue.

**Comment by freddyfernando** [comment]
I'm in for this! Let's see if we can get more traction this time. See you folks there.

**Comment by eddie-knight** [comment]
The (re)inaugural call is only a couple hours away! Closing this issue as complete, and I'll see yall there!
