### ISSUE TITLE
[Presentation] KubeArmor Project Update

### ISSUE THREAD

**Issue by daemon1024** [cncf/tag-security#1372]
Title: KubeArmor Project Update 

Speakers: 
- Barun Acharya (@daemon1024)

Description: It's been 3 years since KubeArmor has been part of CNCF Sandbox and was last presented in WG-Policy. We want to share progress achieved in terms of development, security and adopters in last 3 years and get feedback for incubation(https://github.com/cncf/toc/issues/1326).

Time: How long will the presentation take? (30 min)

Availability: Any timezone

TO DO
- [ ] TAG Representative
- [ ] Schedule date
- [x] By opening this issue, I, @daemon1024  acknowledge that the presentation topic and speaker will follow the [presentation guidelines](../CONTRIBUTING.md#present-to-the-tag)
- [ ] If this is a presentation for a project moving levels, the TAG Representative should complete the [Moving Levels Recommendation](../project-resources/moving-levels-review-template.md)

**Comment by daemon1024** [comment]
Hey @mrcdb 

Oct 9, the AMER call works perfect for us.

**Comment by brandtkeller** [comment]
# TAG recommendation to TOC

## Project Overview

### Ecosystem Adoption

Last 3 years - since Sandbox

30 -> 150+ Contributors
100 -> 1470 stars
30 -> 300 forks

Has seen adoption across Open Source and Enterprise

### Past TOC Reviews

Communication channels was originally a finding and have since been resolved. 

## Security Reviews

### TAG Security Assessments

Informed of the Self and Joint Assessment 

### Security Audit

AccuKnox threat modeling - [link](https://github.com/accuknox/k8sthreatmodeling/blob/main/models/kubearmor/README.md)

Findings resulted items of best practices being resolved

## Best Practices

### Metrics

OpenSSF best Practices 7.9
Fuzz Testing

### Static Analysis

Codeql and GoSec
Other security measures annotated in the repo

## Sub-project Considerations

30 repositories total in the organization

The primary repositories abide by security best practices. 

## TAG Recommendation to the TOC

The project has seen significant growth and adoption since the original acceptance to Sandbox. Having conducted threat modeling and implemented a number of static analysis and security processes in the development lifecycle provides a healthy project stance for security. 

The [self assessment](https://github.com/cncf/tag-security/blob/main/community/assessments/guide/self-assessment.md) is required for projects applying for Incubation in order for the Security TAG to provide a recommendation to the TOC.
