### ISSUE TITLE
document annual review process to update security assessment

### ISSUE THREAD

**Issue by ultrasaurus** [cncf/tag-security#152]
this has been discussed in meetings

well-articulated in [PR comment](https://github.com/cncf/sig-security/pull/125/files/52221a1fbc1c3c21b7922066766f2b7b42ef5c63#r277171055) by @rficcaglia

"I think the notion that a single point in time review ignores the reality that threats change over time. someone using this review process as evidence of "trustworthiness" can be lulled into thinking something is "safe" since it was reviewed N years ago."

**Comment by ultrasaurus** [comment]
It would be great if someone were to draft some text about this and suggest which of our docs it shoul go into, since this keeps coming up as a question

**Comment by rficcaglia** [comment]
Happy to take a stab at it.

**Comment by rficcaglia** [comment]
WIP outline... https://github.com/cncf/sig-security/commit/4fee2816302a7a7719f8f0e3511de575849d190c

**Comment by lumjjb** [comment]
There is some text in https://github.com/cncf/tag-security/blob/main/assessments/intake-process.md for this, is this sufficient for now?

**Comment by lumjjb** [comment]
Needs additional definition of scope.

**Comment by anvega** [comment]
While we recognize this is something we need to get to due to the evolving nature of software projects, it currently exceeds our capacity due to the increased number of projects in the CNCF which correlates to the increased number of projects in the assessments backlog that we need to get to. Should the TOC request a review of projects previously assessed or a new subproject under the same project umbrella, we will prioritize those. In the meantime, we will continue to follow the intake process to prioritize ordering and sequencing of assessments.
