### ISSUE TITLE
landscape: Identity & Access Control category is confusing

### ISSUE THREAD

**Issue by ultrasaurus** [cncf/tag-security#234]
several people have raised the issue that "Identity & Access Control" category is confusing because almost every project must implement access control and use some kind of identity.  

My original understanding of this was that this would be for projects that provide Identity or Access Control, but if that was the intent, it's not clearly described

**Comment by lumjjb** [comment]
>several people have raised the issue that "Identity & Access Control" category is confusing because almost every project must implement access control and use some kind of identity.

Hmm... at least to me, I have the same understanding as you, where this would mean projects that are authn/z providers, not so much users of it.

Every project probably has to have some integration points with such a service, but I think about them like how I think about the use of a database by a project. Ideally, a project would use an "identity and access control service", be it an OAUTH provider or calling out to an RBAC provider/Open Policy Agent instead of rolling their own. - in the later case, it is in itself a red flag.

Maybe i am too missing a perspective.

**Comment by zollman** [comment]
Added a pull request for this - #236 - as well as a review of my own changes. In particular, I like renaming the category Identity Lifecycle and Access Management, from Identity and Access Control - all projects may need to perform authentication and authorization, but no one wants to do "lifecycle" or "management" except those of us that have to.

**Comment by lumjjb** [comment]
>"lifecycle" or "management" 

I am a bit wary of the words "lifecycle" and "management", as they may artificially narrows the scope of projects which intuitively may be in that category. 

For example, Open Policy Agent is usually seen as an authorization service, but it actually relies on additional layers on top of it to do the management of actual authorization policies.

**Comment by omgclouds** [comment]
A bit dry suggestion: Authentication, Authorization, and Accounting Services ?   Otherwise, I agree with Identity and Access Management.  The domain is not limiting the scope of projects.  For instance, calling OPA an authorization and admission controller does not limit its' ability to filter information nor act as a generic policy service.

**Comment by anvega** [comment]
This issue has been stale for several years. Closing this issue as the categories in the landscape have evolved.
