### ISSUE TITLE
[Presentation] Confidential Computing Consortium

### ISSUE THREAD

**Issue by justincormack** [cncf/tag-security#306]
Title: Confidential Computing Consortium overview

Speakers: Stephen Walli @stephenrwalli

Description: The Confidential Computing  Consortium https://confidentialcomputing.io/ is a new Linux Foundation group of projects around how to secure data while in use, so computation and processing can take place without exposing the data to the system or the system providers. I think this would be of interest to SIG Security and CNCF members who may not be aware of the work taking place. They have also adopted a very open governance model compared to other LF projects that may be of interest.

Time: How long will the presentation take? 15-20m

Availability: TBD, January probably

TO DO
- [ ] SIG Representative
- [ ] Schedule date

**Comment by justincormack** [comment]
cc @hannibalhuang

**Comment by lumjjb** [comment]
Any update on this, since issue states January probably.

**Comment by lumjjb** [comment]
Hi @justincormack  @stephenrwalli, following up on this.

**Comment by justincormack** [comment]
Stephen is away again, will try to get a firm date when he is back.

**Comment by IAXES** [comment]
@justincormack Are these presentations ever held outside the weekly (Wednesday) meetings (i.e. if presenter isn't available Wednesdays, for example, record it via Zoom/Webex/etc. and post the recording link), or is it preferable to reschedule and always keep them as live presentations during the weekly meeting? 

Thanks.

**Comment by AevaOnline** [comment]
Apologies, I just found this Issue.

I work closely with @Stephenrwalli within the [CCC](https://confidentialcomputing.io), and was invited to give a presentation in late 2020 on this topic to the SIG. Any SIG member is welcome to follow up with me for coordination, and if I can't answer questions, I'm happy to forward to Stephen or other members of the CCC in our weekly meetings.

@justincormack - should this Issue be closed because the presentation was given or left open for tracking?

**Comment by anvega** [comment]
The presentation already took place.
