### ISSUE TITLE
Mini/Micro blogs to discuss the various aspects of the Cloud Native Security Whitepaper 

### ISSUE THREAD

**Issue by vinayvenkat** [cncf/tag-security#451]
Description: I propose that we write a sequence of mini blogs that delve deeper into the various sections of the Cloud Native Security Whitepaper 

Impact: The obejctive of the blogs will be to dive a deeper into the various sections of the Cloud Native Security Whitepaper. Additionally, provide best practices and guidance for the audience to takeaway in terms of the manner in which security needs to applied at various points in the applications stack as well as the application lifecycle for each dimension as it pertains to security for cloud native applications. 

Scope: TBD
TO DO
- [ ] SIG Representative
- [ ] Project leader(s)
- [ ] TBD

**Comment by magnologan** [comment]
I can help with the blog posts.

**Comment by alok-raj** [comment]
I am interested in writing the blogs.

**Comment by lumjjb** [comment]
@vinayvenkat do you think you could help devise an outline/plan on how we could approach this? If we could start defining a rough scope, it would be facilitate members to find areas to contribute.

**Comment by PushkarJ** [comment]
@vinayvenkat came across one of the articles from you about the whitepaper: https://thenewstack.io/how-to-implement-security-recommendations-from-the-cloud-native-computing-foundation/ Just curious on whether, it is a deliverable of this effort or a separate one ?

**Comment by vinayvenkat** [comment]
> @vinayvenkat came across one of the articles from you about the whitepaper: https://thenewstack.io/how-to-implement-security-recommendations-from-the-cloud-native-computing-foundation/ Just curious on whether, it is a deliverable of this effort or a separate one ?

@PushkarJ This was a separate effort to amplify the reach of the Cloud Native Security Whitepaper

**Comment by PushkarJ** [comment]
Looking at this for v2 whitepaper and v1 retrospective, I think one thing that is clear is that we did not create enough awareness about the whitepaper (40% found out about the whitepaper because of the survey). Having said that, I am not sure if creating a blog series would get us more eyeballs for the effort we would put in. So propose to close this issue in favor of #747 . For completeness, we should continue to do the following things for v2:
- Author CNCF and Kubernetes Blog posts (15% found about whitepaper through them)
- Share the whitepaper through social media, CNCF End user groups and mail subscriptions for members and on https://lists.cncf.io/g/cncf-tag-security

**Comment by anvega** [comment]
We've opted for https://www.cncf.io/blog/ as our avenue to publishing. If you are working on content that you'd like to see featured, just let the rest of us know either in the slack channel or during an upcoming regular call. We'll help you get it published.
