### ISSUE TITLE
[Presentation] Securing Cloud credentials on DevOps machines

### ISSUE THREAD

**Issue by andreacavagna01** [cncf/tag-security#556]
Title: Securing Cloud credentials on DevOps machines

Speakers: @andreacavagna01, @pethron

Description: One of the hardest challenges in a dev-life is to stay productive and confident as the Cloud environment complexity grows. We know that feel. That’s why we count on [Leapp](https://github.com/Noovolari/leapp), our open-source project for the generation and management of secure short-lived credentials to jump into multiple cloud accounts

Time: 30 minutes 

Availability: https://calendly.com/noovolari/30min
TO DO
- [ ] SIG Representative
- [ ] Schedule date

**Comment by anvega** [comment]
Whether this presentation took place needs to be clarified, as I couldn't find it in the meeting notes, given it's been a couple of years, I'll presume it was completed or there was no longer interest in the submitting party to pursue it, or for that, the tag didn't schedule the talk due to availability constraints. I'd encourage you to propose it again if you'd like to share where the project is today. I'll close the issue as it's been inactive for a few years.
