### ISSUE TITLE
Role of Security Operations center in Cloud Native Technologies.

### ISSUE THREAD

**Issue by achetal01** [cncf/tag-security#571]
This is more of developing prescriptive guidance for Enterprises on what the role of SOC teams is in the Cloud Native technology world, where Dev-Sec-OPS should be in place already but yet the teams in dev and ops are still not security experts ....SOC teams traditionally sit outside of the Dev-Sec-OPS.

Maybe we can have a discussion in one of our weekly meetings and get different perspectives on what other enterprises are doing in this space.

**Comment by anvega** [comment]
While an important initiative, since it didn't gather interest or activation, I'll proceed with closing the issue as it's been a few years. It can be explored again if there is renewed interest and willing volunteers to work on it. Perhaps something to suggest during a regular meeting to gauge interest or to plan for the roadmap.
