### ISSUE TITLE
CNSMap Public Comment

### ISSUE THREAD

**Issue by lumjjb** [cncf/tag-security#762]
This thread is open for public comment on the Cloud Native Security Map public Request For Comments. Please put your comments here, the more specific the better! 

If can also create direct PRs on the `cnsmap` branch. More details on how to do this are located here: 
https://github.com/cncf/tag-security/blob/main/security-whitepaper/cnsmap/README.md#contributing-to-the-cnsmap

**Comment by MMerzinger** [comment]
As it is quite a lot of content, I would suggest adding a search bar.

Content:
- I created a small PR that adds Open Service Mesh and removes Trivy from the “Service Mesh” section (see [here](https://github.com/cncf/tag-security/pull/767#issue-981738536)). 
- Not really a security tool, but I think using Buildpacks would be helpful in implementing best practices for Dockerfiles (section Security Checks in Development). Maybe we could add a reference there or mention it in the examples.
- Section “Identity and Access Management” - Maybe we could add a reference to the Dex project as it is quite useful to integrate with OICD provides.

Development issue: If I access “http://localhost:3000/containers” during development (npm run dev), I get an error “Unhandled Runtime Error” as containers.md does not exist. Is this intentional? In the web version on https://cnsmap.netlify.app/containers I get an “An unexpected error has occurred”, but I can still navigate into sub-sections.

**Comment by ashutosh-narkar** [comment]
@MMerzinger can you please open an issue regarding the error you're getting and steps to repro it. Thanks!

**Comment by MMerzinger** [comment]
@ashutosh-narkar sure, opened issue #771 and a proposal in PR #772 to fix it.

**Comment by lumjjb** [comment]
RFC closed
